common: &common
 adapter: postgresql
 encoding: utf8
 host: localhost

development:
 <<: *common
 database: jaivik_dev
 username: jaivik_dev
 password: jaivik_dev

test:
 <<: *common
 database: jaivik_test
 username: jaivik_test
 password: jaivik_test